# Generated by Django 2.0.7 on 2019-01-29 18:09

from django.conf import settings
from django.contrib.sites.models import Site
from django.db import migrations


def create_site(apps, schema_editor):
    current_site = Site.objects.get(pk=1)
    current_site.name = 'Asistente de Cátedra'
    current_site.domain = settings.DOMAIN
    current_site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site,
                             reverse_code=migrations.RunPython.noop)
    ]
