from decouple import config

# Stripe
STRIPE_PRODUCT_ID = config('STRIPE_PRODUCT_ID')
STRIPE_FREE_ID = config('STRIPE_FREE_ID')
STRIPE_MONTHLY_ID = config('STRIPE_MONTHLY_ID')
STRIPE_YEARLY_ID = config('STRIPE_YEARLY_ID')
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
