from django.urls import path
from . import views

urlpatterns = [
     path('', views.PlanificacionesTemplateView.as_view(),
          name="planificaciones"),
     path('plan_clase/list/', views.PlanClaseListView.as_view(),
          name="plan_clase_list"),
     path('plan_clase/create/', views.plan_clase_create,
          name="plan_clase_create"),
     path('plan_clase/update/<int:pk>/<slug:slug>/', views.plan_clase_update,
          name="plan_clase_update"),
     path('plan_clase/delete/<int:pk>/', views.PlanClaseDeleteView.as_view(),
          name="plan_clase_delete"),
     path('plan_clase/duplicate/<int:pk>/',
          views.PlanClaseDuplicateView.as_view(),
          name="plan_clase_duplicate"),
     path('plan_anual/list/', views.PlanAnualListView.as_view(),
          name="plan_anual_list"),
     path('plan_anual/create/', views.PlanAnualCreateView.as_view(),
          name="plan_anual_create"),
     path('plan_anual/update/<int:pk>/<slug:slug>/',
          views.PlanAnualUpdateView.as_view(),
          name="plan_anual_update"),
     path('plan_anual/delete/<int:pk>/', views.PlanAnualDeleteView.as_view(),
          name="plan_anual_delete"),
     path('plan_anual/duplicate/<int:pk>/',
          views.PlanAnualDuplicateView.as_view(),
          name="plan_anual_duplicate"),
     path('plan_unidad/list/', views.PlanUnidadListView.as_view(),
          name="plan_unidad_list"),
     path('plan_unidad/create/',
          views.PlanUnidadCreateView.as_view(),
          name="plan_unidad_create"),
     path('plan_unidad/update/<int:pk>/<slug:slug>/',
          views.PlanUnidadUpdateView.as_view(),
          name="plan_unidad_update"),
     path('plan_unidad/delete/<int:pk>/', views.PlanUnidadDeleteView.as_view(),
          name="plan_unidad_delete"),
     path('plan_unidad/duplicate/<int:pk>/',
          views.PlanUnidadDuplicateView.as_view(),
          name="plan_unidad_duplicate"),
     path('plan_destrezas/list/', views.PlanDestrezasListView.as_view(),
          name="plan_destrezas_list"),
     path('plan_destrezas/create/', views.PlanDestrezasCreateView.as_view(),
          name="plan_destrezas_create"),
     path('plan_destrezas/update/<int:pk>/<slug:slug>/',
          views.PlanDestrezasUpdateView.as_view(),
          name="plan_destrezas_update"),
     path('plan_destrezas/delete/<int:pk>/',
          views.PlanDestrezasDeleteView.as_view(),
          name="plan_destrezas_delete"),
     path('plan_destrezas/duplicate/<int:pk>/',
          views.PlanDestrezasDuplicateView.as_view(),
          name="plan_destrezas_duplicate"),

     # Ajax urls
     # templates: select, checkbox
     path('ajax/cursos/<str:template>/', views.LoadCursosView.as_view(),
          name="ajax_load_cursos"),
     path('ajax/unidades/', views.LoadUnidadesView.as_view(),
          name="ajax_load_unidades"),
     # options: area, curso, unidad
     path('ajax/objetivos/<str:option>/', views.LoadObjetivosView.as_view(),
          name="ajax_load_objetivos"),
     # templates: select, checkbox
     path('ajax/destrezas/<str:template>/<str:formset>/',
          views.LoadDestrezasView.as_view(),
          name="ajax_load_destrezas"),
     path('ajax/criterios/', views.LoadCriteriosView.as_view(),
          name="ajax_load_criterios"),
     # options: destreza, criterio
     path('ajax/indicadores/<str:option>/<str:formset>/',
          views.LoadIndicadoresView.as_view(),
          name="ajax_load_indicadores"),
]
