from django.contrib.messages.storage.fallback import FallbackStorage
from django.contrib.sessions.middleware import SessionMiddleware
from django.core.files.uploadedfile import SimpleUploadedFile
from PIL import Image

from accounts.helpers import empty_folder


def create_test_image(name, size, color=(73, 109, 137),
                      content_type='image/jpeg'):
    """Creates an image for testing purposes"""
    img = Image.new('RGB', size, color=color)
    img.save('tests_media/{}'.format(name))

    img = open('tests_media/{}'.format(name), 'rb')
    img_content = img.read()

    image = SimpleUploadedFile(
        name=name,
        content=img_content,
        content_type=content_type
    )
    img.close()

    return image


def clean_test_files():
    """Cleans all files generated by file tests"""
    folder = 'tests_media/'
    empty_folder(folder)


def add_middleware_to_request(request):
    """
    Función para agregar middleware a un request creado con RequestFactory
    """
    # Add session middleware
    middleware = SessionMiddleware()
    middleware.process_request(request)
    request.session.save()

    # Add messages middleware
    messages = FallbackStorage(request)
    request._messages = messages
    return request
