
import os
import shutil
from PIL import Image
from django.core.files.uploadedfile import SimpleUploadedFile


def create_test_image(name, size, color=(73, 109, 137),
                      content_type='image/jpeg'):
    """Creates an image for testing purposes"""
    img = Image.new('RGB', size, color=color)
    img.save('tests_media/{}'.format(name))

    img = open('tests_media/{}'.format(name), 'rb')
    img_content = img.read()

    image = SimpleUploadedFile(
        name=name,
        content=img_content,
        content_type=content_type
    )
    img.close()

    return image


def clean_test_files():
    """Cleans all files generated by file tests"""
    folder = 'tests_media/'
    for the_file in os.listdir(folder):
        file_path = os.path.join(folder, the_file)

        if os.path.isfile(file_path):
            os.unlink(file_path)
        elif os.path.isdir(file_path):
            shutil.rmtree(file_path)
