# Generated by Django 2.2.1 on 2019-05-28 01:58

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'areas',
                'verbose_name_plural': 'áreas',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='planificaciones.Area')),
            ],
            options={
                'db_table': 'asignaturas',
                'verbose_name_plural': 'asignaturas',
            },
        ),
        migrations.CreateModel(
            name='BloqueCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bloque', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('name', models.CharField(max_length=70)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='planificaciones.Asignatura')),
            ],
            options={
                'db_table': 'bloques_curriculares',
                'verbose_name_plural': 'bloques curriculares',
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=700)),
                ('codigo', models.CharField(max_length=15)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_evaluacion', to='planificaciones.Asignatura')),
            ],
            options={
                'db_table': 'criterios_evaluacion',
                'verbose_name_plural': 'criterios de evaluación',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cursos',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Destreza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400)),
                ('codigo', models.CharField(max_length=15)),
                ('imprescindible', models.BooleanField(default=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destrezas', to='planificaciones.Asignatura')),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destrezas', to='planificaciones.BloqueCurricular')),
            ],
            options={
                'db_table': 'destrezas',
                'verbose_name_plural': 'destrezas',
            },
        ),
        migrations.CreateModel(
            name='ElementoCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conocimientos_asociados', models.TextField(max_length=200)),
                ('actividades_evaluacion', models.TextField(max_length=200)),
                ('destreza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_curriculares', to='planificaciones.Destreza')),
            ],
            options={
                'db_table': 'elementos_curriculares',
                'verbose_name_plural': 'elementos curriculares',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'niveles',
                'verbose_name_plural': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=620)),
                ('codigo', models.CharField(max_length=12)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='planificaciones.Asignatura')),
            ],
            options={
                'db_table': 'objetivos',
                'verbose_name_plural': 'objetivos',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=420)),
                ('codigo', models.CharField(max_length=12)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_generales', to='planificaciones.Area')),
            ],
            options={
                'db_table': 'objetivos_generales',
                'verbose_name_plural': 'objetivos generales',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='planificaciones.Asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='planificaciones.Curso')),
                ('objetivos', models.ManyToManyField(blank=True, related_name='unidades', to='planificaciones.Objetivo')),
                ('objetivos_generales', models.ManyToManyField(blank=True, related_name='unidades', to='planificaciones.ObjetivoGeneral')),
            ],
            options={
                'db_table': 'unidades',
                'verbose_name_plural': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='Subnivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subniveles', to='planificaciones.Nivel')),
            ],
            options={
                'db_table': 'subniveles',
                'verbose_name_plural': 'subniveles',
            },
        ),
        migrations.CreateModel(
            name='ProcesoDidactico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('tiempo', models.CharField(max_length=11)),
                ('recursos', models.TextField(max_length=200)),
                ('elemento_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_didacticos', to='planificaciones.ElementoCurricular')),
            ],
            options={
                'db_table': 'procesos_didacticos',
                'verbose_name_plural': 'procesos didácticos',
            },
        ),
        migrations.CreateModel(
            name='PlanClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('fecha', models.DateField()),
                ('aprobado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=200, null=True)),
                ('numero_plan', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('paralelos', models.CharField(max_length=20)),
                ('numero_estudiantes', models.CharField(max_length=10)),
                ('tema', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(4)])),
                ('periodos', models.CharField(max_length=20)),
                ('metodologia', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(4)])),
                ('tecnica', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('bibliografia', ckeditor.fields.RichTextField()),
                ('contenido_cientifico', ckeditor_uploader.fields.RichTextUploadingField()),
                ('material_didactico', ckeditor_uploader.fields.RichTextUploadingField()),
                ('instrumento_evaluacion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones', to='planificaciones.Asignatura')),
                ('cursos', models.ManyToManyField(related_name='planificaciones', to='planificaciones.Curso')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to=settings.AUTH_USER_MODEL)),
                ('objetivos', models.ManyToManyField(blank=True, related_name='planes_clase', to='planificaciones.Objetivo')),
                ('objetivos_generales', models.ManyToManyField(blank=True, related_name='planes_clase', to='planificaciones.ObjetivoGeneral')),
            ],
            options={
                'db_table': 'planes_clase',
                'verbose_name_plural': 'planes de clase',
            },
        ),
        migrations.AddField(
            model_name='objetivo',
            name='subnivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='planificaciones.Subnivel'),
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=700)),
                ('codigo', models.CharField(max_length=15)),
                ('criterio_evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicadores', to='planificaciones.CriterioEvaluacion')),
            ],
            options={
                'db_table': 'indicadores',
                'verbose_name_plural': 'indicadores',
            },
        ),
        migrations.AddField(
            model_name='elementocurricular',
            name='indicadores_logro',
            field=models.ManyToManyField(related_name='elementos_curriculares', to='planificaciones.Indicador'),
        ),
        migrations.AddField(
            model_name='elementocurricular',
            name='plan_clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_curriculares', to='planificaciones.PlanClase'),
        ),
        migrations.AddField(
            model_name='destreza',
            name='subnivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destrezas', to='planificaciones.Subnivel'),
        ),
        migrations.AddField(
            model_name='curso',
            name='subnivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='planificaciones.Subnivel'),
        ),
        migrations.AddField(
            model_name='criterioevaluacion',
            name='destrezas',
            field=models.ManyToManyField(related_name='criterios_evaluacion', to='planificaciones.Destreza'),
        ),
        migrations.AddField(
            model_name='criterioevaluacion',
            name='objetivos_generales',
            field=models.ManyToManyField(related_name='criterios_evaluacion', to='planificaciones.ObjetivoGeneral'),
        ),
        migrations.AddField(
            model_name='criterioevaluacion',
            name='subnivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_evaluacion', to='planificaciones.Subnivel'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='asignaturas', to='planificaciones.Curso'),
        ),
    ]
